'use client';
import { useEffect, useState, useTransition } from 'react';
import type { AuditEvent, SettlementItemRecord, SettlementRecord } from '@gps/settlement';
import { PaymentGraph } from './payment-graph';
import { InvoiceFields } from './invoice-fields';
import { PolicyEditor } from './policy-editor';
type View={settlement:SettlementRecord;items:Array<SettlementItemRecord&{hasInvoice:boolean}>;events:AuditEvent[];receipts:Record<string,unknown>[];ledgerValid:boolean;mode:'mock'|'testnet'};
type Tab='flow'|'policy'|'receipts';
export function ConsoleApp(){
 const[data,setData]=useState<View>(),[tab,setTab]=useState<Tab>('flow'),[confirm,setConfirm]=useState(''),[error,setError]=useState('');const[pending,start]=useTransition();
 useEffect(()=>{fetch('/api/settlements').then(r=>r.json()).then(setData);const es=new EventSource('/api/events');es.onmessage=e=>setData(JSON.parse(e.data)as View);return()=>es.close()},[]);
 if(!data)return <main className="aura-loading"><div className="aura-orb">A</div><p>Opening your payment space…</p></main>;
 const mutate=(action:string)=>start(async()=>{setError('');const r=await fetch('/api/settlements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:data.settlement.id,action,confirmation:confirm})}),j=await r.json()as View&{error?:string};if(!r.ok)setError(j.error??'Request failed');else setData(j)});
 const success=data.items.filter(i=>i.status==='SUCCEEDED').length,totalFees=data.items.reduce((sum,i)=>sum+(i.actualFeeSat??0),0);
 return <div className="aura-shell"><div className="ambient ambient-one"/><div className="ambient ambient-two"/><header className="aura-header"><button className="aura-brand" onClick={()=>setTab('flow')} aria-label="Aura home"><span className="aura-logo"><i/><i/><i/></span><span><b>Aura</b><small>value flows with intention</small></span></button><nav aria-label="Primary"><button className={tab==='flow'?'selected':''} onClick={()=>setTab('flow')}>Flow</button><button className={tab==='policy'?'selected':''} onClick={()=>setTab('policy')}>Policies</button><button className={tab==='receipts'?'selected':''} onClick={()=>setTab('receipts')}>Receipts</button></nav><div className="header-actions"><span className={`mode-badge ${data.mode}`}>{data.mode==='mock'?'MOCK SPACE':'BITCOIN TESTNET'}</span><button className="profile-orb" aria-label="Open profile">A</button></div></header><main className="aura-main">
 {tab==='flow'?<><section className="hero"><div><span className="eyebrow">AURA PAYMENT FLOW</span><h1>Move value with clarity.</h1><p>One agreement, many recipients, every movement visible.</p></div><button className="aura-button" onClick={()=>setTab('policy')}>＋ Create a policy</button></section><section className="summary-glass"><Metric label="Settlement" value="Aura Test Sale"/><Metric label="Value" value={`${data.settlement.grossSat.toLocaleString()} sats`}/><Metric label="Recipients" value={`${success}/${data.items.length}`}/><Metric label="Fees" value={`${totalFees} sats`}/><Metric label="Integrity" value={data.ledgerValid?'Verified':'Attention'} tone={data.ledgerValid?'good':'bad'}/></section><section className="glass flow-card"><div className="section-heading"><div><span className="eyebrow">LIVE MAP</span><h2>Payment constellation</h2></div><div className="flow-state"><span className="pulse"/>{humanize(data.settlement.status)}</div></div><PaymentGraph settlement={data.settlement} items={data.items}/></section>{data.mode==='testnet'&&data.settlement.status==='AWAITING_INVOICES'?<section className="glass invoice-panel"><InvoiceFields settlementId={data.settlement.id} items={data.items} onUpdated={v=>setData(v as View)}/></section>:null}<section className="lower-grid"><article className="glass approval-card"><span className="eyebrow">YOUR APPROVAL</span><h2>Ready when you are</h2><p>These are {data.items.length} independent payments. A partial settlement is possible.</p><div className="approval-meta"><span>Maximum fees</span><b>{data.settlement.maxTotalFeeSat} sats</b></div><label>Write <b>TESTNET</b> to continue<input value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="TESTNET"/></label><div className="approval-actions"><button className="soft-button" onClick={()=>mutate('approve')} disabled={data.settlement.status!=='READY_FOR_APPROVAL'||confirm!=='TESTNET'||pending}>Approve flow</button><button className="aura-button" onClick={()=>mutate('execute')} disabled={data.settlement.status!=='APPROVED'||pending}>Release payments →</button></div>{error?<p className="form-error" role="alert">{error}</p>:null}</article><article className="glass timeline-card"><div className="section-heading"><div><span className="eyebrow">TRACE</span><h2>What happened</h2></div><span>{data.events.length} moments</span></div><div className="aura-timeline">{data.events.slice(-7).reverse().map((event,index)=><div key={event.id}><span className={index===0?'current':''}/><p><b>{humanize(event.type)}</b><small>{new Date(event.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></p></div>)}</div></article></section></>:null}
 {tab==='policy'?<><section className="hero compact"><div><span className="eyebrow">POLICIES</span><h1>Design your value ritual.</h1><p>Add recipients, tune weights, and see the split before signing.</p></div></section><PolicyEditor/></>:null}
 {tab==='receipts'?<><section className="hero compact"><div><span className="eyebrow">AUDITABLE RECEIPTS</span><h1>A clear memory of every flow.</h1><p>Signed evidence, connected in order.</p></div></section><section className="glass receipt-space"><div className="integrity-orb">{data.ledgerValid?'✓':'!'}</div><div><span className="eyebrow">LEDGER INTEGRITY</span><h2>{data.ledgerValid?'The chain is verified':'Verification needs attention'}</h2><p>{data.receipts.length} persisted entries in this settlement.</p></div><button className="soft-button" onClick={()=>download(data.receipts)}>Export JSON ↓</button></section></>:null}
 </main><footer className="aura-footer"><span>Aura · Human-approved payment orchestration</span><span>{data.mode==='mock'?'Mock payments — no funds move':'Bitcoin testnet has no monetary value'}</span></footer></div>
}
function Metric({label,value,tone}:{label:string;value:string;tone?:string}){return <div><span>{label}</span><b className={tone}>{value}</b></div>}
function humanize(value:string){return value.toLowerCase().replaceAll('_',' ').replace(/^./,c=>c.toUpperCase())}
function download(receipts:Record<string,unknown>[]){const blob=new Blob([JSON.stringify(receipts,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='aura-receipts.json';a.click();URL.revokeObjectURL(a.href)}
