'use client';
import { useEffect, useMemo, useState } from 'react';
type PolicyRow={id:string;name:string;role:string;weight:number};
const defaults:PolicyRow[]=[{id:'provider',name:'Aura Provider',role:'Provider',weight:70},{id:'referrer',name:'Referral Partner',role:'Referrer',weight:20},{id:'community',name:'Community Fund',role:'Community',weight:10}];
const STORAGE_KEY='gps:aura-policy:v1';
export function PolicyEditor(){
 const[title,setTitle]=useState('Aura Test Sale'),[gross,setGross]=useState(100001),[rows,setRows]=useState<PolicyRow[]>(defaults),[saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const parsed=JSON.parse(raw)as{version:number;title:string;gross:number;rows:PolicyRow[]};if(parsed.version===1){setTitle(parsed.title);setGross(parsed.gross);setRows(parsed.rows)}}}catch{/* Invalid local drafts are ignored. */}},[]);
 const total=rows.reduce((sum,row)=>sum+row.weight,0),amounts=useMemo(()=>{if(total<=0)return rows.map(()=>0);const exact=rows.map(r=>gross*r.weight/total),floors=exact.map(Math.floor);let rest=gross-floors.reduce((a,b)=>a+b,0);return floors.map((v,index)=>v+(rest-->0?1:0))},[gross,rows,total]);
 function patch(id:string,next:Partial<PolicyRow>){setSaved(false);setRows(current=>current.map(row=>row.id===id?{...row,...next}:row))}
 function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({version:1,title,gross,rows}));setSaved(true)}
 return <section className="glass policy-card" aria-labelledby="policy-title"><div className="section-heading"><div><span className="eyebrow">PAYMENT POLICY</span><h2 id="policy-title">Shape how value flows</h2><p>Edit this local draft before creating your next signed agreement.</p></div><div className={`sum-pill ${total===100?'balanced':'unbalanced'}`}><span>Total weight</span><b>{total}%</b></div></div><div className="policy-basics"><label>Policy name<input value={title} onChange={e=>{setTitle(e.target.value);setSaved(false)}}/></label><label>Gross amount<div className="sat-input"><input type="number" min="1" value={gross} onChange={e=>{setGross(Math.max(1,Number(e.target.value)));setSaved(false)}}/><span>sats</span></div></label></div><div className="policy-rows">{rows.map((row,index)=><article className="policy-row" key={row.id}><div className="avatar">{String(index+1).padStart(2,'0')}</div><label><span>Recipient</span><input value={row.name} onChange={e=>patch(row.id,{name:e.target.value})}/></label><label><span>Role</span><input value={row.role} onChange={e=>patch(row.id,{role:e.target.value})}/></label><label className="weight"><span>Weight</span><div><input type="number" min="0" max="100" value={row.weight} onChange={e=>patch(row.id,{weight:Math.max(0,Number(e.target.value))})}/><span>%</span></div></label><div className="row-amount"><span>Receives</span><b>{amounts[index]?.toLocaleString()} sats</b></div><button className="icon-button" aria-label={`Remove ${row.name}`} onClick={()=>setRows(current=>current.filter(item=>item.id!==row.id))}>×</button></article>)}</div><div className="policy-footer"><button className="ghost-button" onClick={()=>setRows(current=>[...current,{id:crypto.randomUUID(),name:'New recipient',role:'Contributor',weight:0}])}><span>＋</span> Add payment recipient</button><div><span className={total===100?'balance-ok':'balance-warn'}>{total===100?'Balanced and ready':'Weights are normalized in preview'}</span><button className="aura-button" onClick={save}>{saved?'Draft saved ✓':'Save policy draft'}</button></div></div></section>
}
