import{randomUUID}from'node:crypto';import{computeAmounts,verifyAgreement,ReceiptLedger,type Agreement}from'@luca/gps-core';import{InvoiceValidationError,SettlementError}from'./errors.js';import{deriveIdempotencyKey,sha256}from'./idempotency.js';import type{PaymentRail,SettlementRepository}from'./ports.js';import type{AuditEventType,PaymentUpdate,SettlementItemRecord,SettlementRecord}from'./types.js';
export interface Limits{maxPaymentSat:number;maxSettlementSat:number;maxFeeSat:number}
export class SettlementService{
 constructor(private repo:SettlementRepository,private rail:PaymentRail,private ledger:ReceiptLedger,private limits:Limits,private payerPubkey?:string){}
 private event(s:string,type:AuditEventType,metadata:Record<string,unknown>={},item?:string){this.repo.addEvent({id:randomUUID(),settlementId:s,type,metadata,...item?{settlementItemId:item}:{},createdAt:new Date().toISOString()})}
 createPlan(a:Agreement,grossSat:number,names:Record<string,string>,network:'mock'|'testnet'){
  if(!verifyAgreement(a))throw new SettlementError('INVALID_AGREEMENT','Agreement signature is invalid');if(!Number.isInteger(grossSat)||grossSat<=0||grossSat>this.limits.maxSettlementSat)throw new SettlementError('PAYMENT_LIMIT_EXCEEDED','Gross exceeds configured limit');
  const id=randomUUID(),rows=computeAmounts(a,grossSat),s:SettlementRecord={id,agreementId:a.agreement_id,grossSat,network,status:network==='mock'?'READY_FOR_APPROVAL':'AWAITING_INVOICES',maxTotalFeeSat:this.limits.maxFeeSat*rows.length,snapshotJson:JSON.stringify({roles:a.pinned_roles,bindings:a.bindings,policyVersion:a.policy_ref.version,agreementSignature:a.sig,memo:a.memo}),createdAt:new Date().toISOString()};
  const items=rows.map((r):SettlementItemRecord=>({id:randomUUID(),settlementId:id,role:r.role,recipientDid:r.did,recipientName:names[r.did]??r.role,weight:r.weight,amountSat:r.amount_sat,status:network==='mock'?'READY':'PENDING_INVOICE',feeLimitSat:this.limits.maxFeeSat}));this.repo.createSettlement(s,items);this.event(id,'SETTLEMENT_CREATED',{grossSat,network,itemCount:items.length});return s;
 }
 async attachInvoice(sid:string,iid:string,invoice:string){const s=this.mustS(sid),i=this.mustI(iid);if(i.settlementId!==sid||s.network!=='testnet'||s.status!=='AWAITING_INVOICES')throw new SettlementError('INVALID_STATE','Not awaiting testnet invoices');let d;try{d=await this.rail.decodeInvoice(invoice)}catch{throw new InvoiceValidationError('INVALID_INVOICE','Invoice cannot be decoded')}if(d.network!=='testnet')throw new InvoiceValidationError('WRONG_NETWORK','Only testnet invoices are accepted');if(d.amountSat===null)throw new InvoiceValidationError('INVALID_INVOICE','Amountless invoice');if(d.amountSat!==i.amountSat)throw new InvoiceValidationError('AMOUNT_MISMATCH',`Invoice must be ${i.amountSat} sat`);if(Date.parse(d.expiresAt)<=Date.now())throw new InvoiceValidationError('INVOICE_EXPIRED','Invoice expired');if(i.amountSat>this.limits.maxPaymentSat)throw new InvoiceValidationError('PAYMENT_LIMIT_EXCEEDED','Payment limit exceeded');if(this.payerPubkey&&d.destination===this.payerPubkey)throw new InvoiceValidationError('SELF_PAYMENT_FORBIDDEN','Self-payment forbidden');const ih=sha256(invoice);if(this.repo.invoiceHashExists(ih,iid))throw new InvoiceValidationError('DUPLICATE_INVOICE','Duplicate invoice');if(this.repo.getAttemptByHash(d.paymentHash))throw new InvoiceValidationError('PAYMENT_ALREADY_EXISTS','Payment hash already exists');this.repo.updateItem(iid,{invoice,invoiceHash:ih,paymentHash:d.paymentHash,status:'READY'});this.event(sid,'INVOICE_ATTACHED',{invoiceHash:ih},iid);this.event(sid,'INVOICE_VALIDATED',{paymentHash:d.paymentHash},iid);if(this.repo.getItems(sid).every(x=>x.id===iid||x.status==='READY'))this.repo.updateSettlement(sid,{status:'READY_FOR_APPROVAL'})}
 approve(id:string,confirmation:string){const s=this.mustS(id);if(s.status!=='READY_FOR_APPROVAL'||confirmation!=='TESTNET')throw new SettlementError('APPROVAL_REQUIRED','Backend approval requires TESTNET');const approvedAt=new Date().toISOString();this.repo.updateSettlement(id,{status:'APPROVED',approvedAt});this.event(id,'APPROVAL_GRANTED')}
 async execute(id:string){const s=this.mustS(id);if(s.status!=='APPROVED')throw new SettlementError('APPROVAL_REQUIRED','Backend approval required');this.repo.updateSettlement(id,{status:'EXECUTING'});this.event(id,'EXECUTION_STARTED');let ok=0,stop=false;for(const i of this.repo.getItems(id)){if(stop){this.repo.updateItem(i.id,{status:'SKIPPED'});this.event(id,'ITEM_SKIPPED',{},i.id);continue}const u=await this.executeItem(s,i);if(u.status==='SUCCEEDED')ok++;else stop=true}const items=this.repo.getItems(id),completedAt=new Date().toISOString();if(ok===items.length){this.repo.updateSettlement(id,{status:'SUCCEEDED',completedAt});this.receipt(id,'settlement_complete',{settlement_id:id,agreement_id:s.agreementId});this.event(id,'SETTLEMENT_SUCCEEDED')}else if(ok){this.repo.updateSettlement(id,{status:'PARTIALLY_SETTLED',completedAt});this.receipt(id,'settlement_partial',{settlement_id:id,agreement_id:s.agreementId,succeeded:ok,total:items.length});this.event(id,'SETTLEMENT_PARTIAL',{succeeded:ok})}else{this.repo.updateSettlement(id,{status:'FAILED',completedAt});this.event(id,'SETTLEMENT_FAILED')}return this.mustS(id)}
 private async executeItem(s:SettlementRecord,i:SettlementItemRecord){if(s.network==='mock'&&!i.invoice){const hash=sha256(`${s.id}:${i.id}:mock`);this.repo.updateItem(i.id,{invoice:'mock-payment',invoiceHash:hash,paymentHash:hash})}i=this.mustI(i.id);if(!i.invoice||!i.paymentHash||!i.invoiceHash)throw new SettlementError('INVOICE_REQUIRED','Invoice required');const previous=this.repo.getAttemptByHash(i.paymentHash);if(previous)return this.finish(s,i,await this.rail.trackPayment(i.paymentHash,u=>this.update(s,i,u)));const now=new Date().toISOString(),a={id:randomUUID(),settlementItemId:i.id,idempotencyKey:deriveIdempotencyKey(s.id,i.id,i.paymentHash,i.amountSat),paymentHash:i.paymentHash,status:'PAYING',createdAt:now,updatedAt:now};if(!this.repo.createAttempt(a))return this.finish(s,i,await this.rail.trackPayment(i.paymentHash,u=>this.update(s,i,u)));this.repo.updateItem(i.id,{status:'PAYING',startedAt:now});this.event(s.id,'PAYMENT_STARTED',{paymentHash:i.paymentHash},i.id);return this.finish(s,i,await this.rail.pay(i.invoice,i.feeLimitSat,u=>this.update(s,i,u)))}
 private async update(s:SettlementRecord,i:SettlementItemRecord,u:PaymentUpdate){if(u.status==='IN_FLIGHT'){this.repo.updateItem(i.id,{status:'IN_FLIGHT'});this.event(s.id,'PAYMENT_IN_FLIGHT',{},i.id)}}
 private finish(s:SettlementRecord,i:SettlementItemRecord,u:PaymentUpdate){const a=this.repo.getAttemptByHash(u.paymentHash),now=new Date().toISOString();if(a)this.repo.updateAttempt(a.id,{status:u.status,...u.paymentIndex?{lndPaymentIndex:u.paymentIndex}:{},...u.failureReason?{failureReason:u.failureReason}:{},updatedAt:now});if(u.status==='SUCCEEDED'){this.repo.updateItem(i.id,{status:'SUCCEEDED',actualFeeSat:u.feeSat,completedAt:now});this.event(s.id,'PAYMENT_SUCCEEDED',{paymentHash:u.paymentHash,feeSat:u.feeSat},i.id);this.receipt(s.id,'split_receipt',{settlement_id:s.id,agreement_id:s.agreementId,policy_version:JSON.parse(s.snapshotJson).policyVersion,role:i.role,recipient_did:i.recipientDid,amount_sat:i.amountSat,fee_sat:u.feeSat,rail:s.network==='mock'?'mock':'lightning-lnd',network:s.network,payment_hash:u.paymentHash,invoice_hash:i.invoiceHash,evidence:{payment_preimage:u.paymentPreimage,payment_index:u.paymentIndex},settled_at:now})}else if(u.status==='FAILED'){this.repo.updateItem(i.id,{status:'FAILED',failureCode:'PAYMENT_FAILED',failureMessage:u.failureReason??'Payment failed',completedAt:now});this.event(s.id,'PAYMENT_FAILED',{reason:u.failureReason??'unknown'},i.id);this.receipt(s.id,'settlement_failed',{settlement_id:s.id,agreement_id:s.agreementId,role:i.role,payment_hash:u.paymentHash})}else{this.repo.updateItem(i.id,{status:'UNKNOWN',failureCode:'PAYMENT_UNKNOWN',completedAt:now});this.event(s.id,'PAYMENT_UNKNOWN',{},i.id);this.receipt(s.id,'settlement_unknown',{settlement_id:s.id,agreement_id:s.agreementId,role:i.role,payment_hash:u.paymentHash})}return u}
 private receipt(id:string,k:string,b:Record<string,unknown>){this.repo.saveReceipt(id,this.ledger.append(k,b))} private mustS(id:string){const x=this.repo.getSettlement(id);if(!x)throw new SettlementError('NOT_FOUND','Settlement not found');return x} private mustI(id:string){const x=this.repo.getItem(id);if(!x)throw new SettlementError('NOT_FOUND','Item not found');return x} verifyLedger(id:string){const valid=this.ledger.verifyChain();this.event(id,'LEDGER_VERIFIED',{valid});return valid}
}
